[package]
name = "time-to-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
color-eyre = "0.6"
eyre = "0.6"
serenity = { version = "0.11" }
tokio = { version = "1.21", features = ["rt", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
